// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFkWr5x8YE-U5lhpdMterU0J896setFs',
    appId: '1:870937751708:web:8eb676185224408fe9fd59',
    messagingSenderId: '870937751708',
    projectId: 'firstproject-b01e4',
    authDomain: 'firstproject-b01e4.firebaseapp.com',
    storageBucket: 'firstproject-b01e4.appspot.com',
    measurementId: 'G-M2KBHQGYYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD1dRjyb9oTmIrrNp-3yv050FC1H2ACVE',
    appId: '1:870937751708:android:c484114e1af90d75e9fd59',
    messagingSenderId: '870937751708',
    projectId: 'firstproject-b01e4',
    storageBucket: 'firstproject-b01e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtjfSsifNAL-oEooeDC2jegURvONy4Fj8',
    appId: '1:870937751708:ios:fddf59d27e7d3025e9fd59',
    messagingSenderId: '870937751708',
    projectId: 'firstproject-b01e4',
    storageBucket: 'firstproject-b01e4.appspot.com',
    iosClientId: '870937751708-jpeimvpbbc6srsikn7mrfauhsu88kpii.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseconnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtjfSsifNAL-oEooeDC2jegURvONy4Fj8',
    appId: '1:870937751708:ios:621e7dab45d922a6e9fd59',
    messagingSenderId: '870937751708',
    projectId: 'firstproject-b01e4',
    storageBucket: 'firstproject-b01e4.appspot.com',
    iosClientId: '870937751708-c1gpu2kmtspkmj19p5slkaabfm5h2rk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseconnection.RunnerTests',
  );
}
